[build]
  publish = "."
  command = ""
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 

[build.environment]
  OPENAI_API_KEY = "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"